<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2008/11/25 17:31:50


$this->setDatabase('propel', new sfPropelDatabase(array (
  'dsn' => 'mssql://student:password@boris.cs.columbia.edu/Genspace',
  'name' => 'propel',
)));
