<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2008/12/10 13:22:32
sfConfig::set('sf_compat_10', true);
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoWorkflow_ratings/actions/actions.class.php');

