<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2008/11/25 20:23:19
sfConfig::set('sf_compat_10', true);
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoRegistration/actions/actions.class.php');

