<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2008/12/08 22:37:11
sfConfig::set('sf_compat_10', true);
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoTool_comments/actions/actions.class.php');

