all:
 
     propel:
       class:          sfPropelDatabase
       param:
         classname: PropelPDO
         dsn:     mysql:dbname=genspace;host=127.0.0.1
         username: genspace
         password: g3nsp4c3
         encoding: 