all:
 
     propel:
       class:          sfPropelDatabase
       param:
         classname: MssqlPropelPDO
         dsn:          mssql:dbname=Genspace;host=boris.cs.columbia.edu
         username: student
         password: password
         encoding: 