<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/12/23 13:42:01
$this->connect('static', '/static/:content', array (
  'module' => 'static',
  'action' => 'index',
), array());
$this->connect('tool_detail', 'tool/index/:id', array (
  'module' => 'tool',
  'action' => 'index',
), array());
$this->connect('workflow_detail', 'workflow/index/:id', array (
  'module' => 'workflow',
  'action' => 'index',
), array());
$this->connect('homepage', '/', array (
  'module' => 'static',
  'action' => 'index',
), array());
$this->connect('default_symfony', '/symfony/:action/*', array (
  'module' => 'default',
), array());
$this->connect('default_index', '/:module', array (
  'action' => 'index',
), array());
$this->connect('default', '/:module/:action/*', array(), array());
