<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/18 01:24:56

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=genspace;host=127.0.0.1',
  'username' => 'genspace',
  'password' => 'g3nsp4c3',
  'encoding' => NULL,
  'name' => 'propel',
)),);
