<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/12 17:20:37

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=genspace;host=127.0.0.1',
  'username' => 'genspace',
  'password' => 'g3nsp4c3',
  'encoding' => NULL,
  'name' => 'propel',
)),);
