<?php
// auto-generated by sfCacheConfigHandler
// date: 2011/05/12 17:20:37
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));

