<?php
// auto-generated by sfCacheConfigHandler
// date: 2011/01/01 13:38:59
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));

