<?php
// auto-generated by sfCacheConfigHandler
// date: 2011/04/18 01:26:41
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));

