<?php
// auto-generated by sfCacheConfigHandler
// date: 2010/12/21 13:33:08
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));

