rendering:
  class: sfRenderingFilter
  param:
    type: rendering

security:
  enabled: false

cache:
  class: sfCacheFilter
  param:
    condition: %SF_CACHE%

execution:
  class:  sfExecutionFilter
  param:
    type: execution

